REFERENCE: /tsl/data/sequences/plants/s_lycopersicum/Solanum_lycopersicum.SL3.0.dna.toplevel.fa
datafolder: /tsl/data/extReads/lila_grandgeorge
        # - SRR5405163--DNase-Hypersensitivity--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--rin_leaf_DNase-seq_3--leaf--not_collected
        # - SRR5405164--DNase-Hypersensitivity--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--rin_leaf_DNase-seq_2--leaf--not_collected
        # - SRR5405165--DNase-Hypersensitivity--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--rin_leaf_DNase-seq_1--leaf--not_collected
        # - SRR5405170--DNase-Hypersensitivity--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--nr_leaf_DNase-seq_2--leaf--not_collected
        # - SRR5405171--DNase-Hypersensitivity--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--nr_leaf_DNase-seq_1--leaf--not_collected
        # - SRR5405176--DNase-Hypersensitivity--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--nor_leaf_DNase-seq_3--leaf--not_collected
        # - SRR5405177--DNase-Hypersensitivity--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--nor_leaf_DNase-seq_2--leaf--not_collected
        # - SRR5405178--DNase-Hypersensitivity--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--nor_leaf_DNase-seq_1--leaf--not_collected
        # - SRR5405196--DNase-Hypersensitivity--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--Lichun_leaf_DNase-seq_4--leaf--not_collected
        # - SRR5405197--DNase-Hypersensitivity--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--Lichun_leaf_DNase-seq_3--leaf--not_collected
        # - SRR5405198--DNase-Hypersensitivity--Illumina_HiSeq_4000--SINGLE--Solanum_lycopersicum--Lichun_leaf_DNase-seq_2--leaf--not_collected
        # - SRR5405199--DNase-Hypersensitivity--Illumina_HiSeq_4000--SINGLE--Solanum_lycopersicum--Lichun_leaf_DNase-seq_1--leaf--not_collected
        # - SRR5405204--DNase-Hypersensitivity--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--cnr_leaf_DNase-seq_2--leaf--not_collected
        # - SRR5405205--DNase-Hypersensitivity--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--cnr_leaf_DNase-seq_1--leaf--not_collected
        # - SRR5405211--DNase-Hypersensitivity--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--AC_leaf_DNase-seq_4--leaf--not_collected
        # - SRR5405212--DNase-Hypersensitivity--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--AC_leaf_DNase-seq_3--leaf--not_collected
        # - SRR5405213--DNase-Hypersensitivity--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--AC_leaf_DNase-seq_2--leaf--not_collected
        # - SRR5405214--DNase-Hypersensitivity--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--AC_leaf_DNase-seq_1--leaf--not_collected
        # - SRR5405215--DNase-Hypersensitivity--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--AC_leaf_DNase-seq_7--leaf--not_collected
        # - SRR5405216--DNase-Hypersensitivity--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--AC_leaf_DNase-seq_6--leaf--not_collected
        # - SRR5405217--DNase-Hypersensitivity--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--AC_leaf_DNase-seq_5--leaf--not_collected
        # - SRR5405329--ChIP-Seq--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--AC_leaf_H3K27me3_2--leaf--not_collected
        # - SRR5405330--ChIP-Seq--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--AC_leaf_H3K27me3_1--leaf--not_collected
        # - SRR5748725--HiC--Hong_Kong--SlMC_HiC_1.1.1--17961--SRS2307840--SRP110225--leaf_mesophyll
        # - SRR5748726--HiC--Hong_Kong--SlMC_HiC_1.1.2--16202--SRS2307837--SRP110225--leaf_mesophyll
        # - SRR5748727--ChIP-Seq--Hong_Kong--SlMC_H3K27ac_1.1--1454--SRS2307836--SRP110225--leaf_mesophyll
        # - SRR5748728--ChIP-Seq--Hong_Kong--SlMC_H3K27ac_1.2--1731--SRS2307835--SRP110225--leaf_mesophyll
        # - SRR5748729--HiC--Hong_Kong--SlMC_HiC_1.2.1--9968--SRS2307834--SRP110225--leaf_mesophyll
        # - SRR5748730--HiC--Hong_Kong--SlMC_HiC_1.2.2--13019--SRS2307833--SRP110225--leaf_mesophyll
        # - SRR5748731--HiC--Hong_Kong--SlMC_HiC_2.1.1--13780--SRS2307832--SRP110225--leaf_mesophyll
        # - SRR5748732--HiC--Hong_Kong--SlMC_HiC_2.1.2--25824--SRS2307831--SRP110225--leaf_mesophyll
        # - SRR5748733--HiC--Hong_Kong--SlMC_HiC_2.2.1--8869--SRS2307829--SRP110225--leaf_mesophyll
        # - SRR5748734--HiC--Hong_Kong--SlMC_HiC_2.2.2--5856--SRS2307830--SRP110225--leaf_mesophyll
        # - SRR5748735--HiC--Hong_Kong--SlMC_HiC_2.2.4--1613--SRS2307828--SRP110225--leaf_mesophyll
        # - SRR5748736--HiC--Hong_Kong--SlMC_HiC_2.2.3--677--SRS2307827--SRP110225--leaf_mesophyll
        # - SRR6320485--RNA-Seq--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--AC_leaf_adult_RNA-seq_2--leaf--adult
        # - SRR6320490--RNA-Seq--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--AC_leaf_young_RNA-seq_1--leaf--young
        # - SRR6320492--RNA-Seq--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--AC_leaf_adult_RNA-seq_1--leaf--adult
        # - SRR6320493--RNA-Seq--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--AC_leaf_young_RNA-seq_2--leaf--young
        # - SRR6320513--ChIP-Seq--Illumina_HiSeq_2000--SINGLE--Solanum_lycopersicum--AC_leaf_H3K4me3_1--leaf--not_collected
        # - SRR6320514--ChIP-Seq--Illumina_HiSeq_2000--SINGLE--Solanum_lycopersicum--AC_leaf_H3K4me3_2--leaf--not_collected
        # - SRR6320543--ChIP-Seq--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--AC_leaf_H3K27ac_6--leaf--not_collected
        # - SRR6320545--ChIP-Seq--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--AC_leaf_H3K27ac_4--leaf--not_collected
        # - SRR6320546--ChIP-Seq--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--AC_leaf_H3K27ac_5--leaf--not_collected
        # - SRR6320547--ChIP-Seq--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--AC_leaf_H3K27ac_2--leaf--not_collected
        # - SRR6320548--ChIP-Seq--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--AC_leaf_H3K27ac_3--leaf--not_collected
        # - SRR6320570--ChIP-Seq--HiSeq_X_Ten--PAIRED--Solanum_lycopersicum--AC_leaf_H3K27ac_1--leaf--not_collected
        # - SRR6322633--Bisulfite-Seq--Hong_Kong--SlMC_BS_1.2--4946--SRS2714151--SRP110225--leaf_mesophyll
        # - SRR6322634--Bisulfite-Seq--Hong_Kong--SlMC_BS_1.1--1590--SRS2714150--SRP110225--leaf_mesophyll
        # - SRR6322635--Bisulfite-Seq--Hong_Kong--SlMC_BS_2.2--9401--SRS2714149--SRP110225--leaf_mesophyll
        # - SRR6322636--Bisulfite-Seq--Hong_Kong--SlMC_BS_2.1--2686--SRS2714148--SRP110225--leaf_mesophyll
        # - SRR7647226--ChIP-Seq--Illumina_HiSeq_2000--SINGLE--Solanum_lycopersicum--AC_leaf_H3K4me3_Cornell_1--leaf--leaf
        # - SRR7647227--ChIP-Seq--Illumina_HiSeq_2000--SINGLE--Solanum_lycopersicum--AC_leaf_H3K4me3_Cornell_2--leaf--leaf
        # - SRR7647250--ChIP-Seq--Illumina_HiSeq_2000--SINGLE--Solanum_lycopersicum--AC_leaf_H3K27me3_Cornell_2--leaf--leaf
        # - SRR7647251--ChIP-Seq--Illumina_HiSeq_2000--SINGLE--Solanum_lycopersicum--AC_leaf_H3K27me3_Cornell_1--leaf--leaf
        # - SRR7647255--ChIP-Seq--Illumina_HiSeq_2000--SINGLE--Solanum_lycopersicum--AC_leaf_H3K27me3_Cornell_4--leaf--leaf
        # - SRR7647256--ChIP-Seq--Illumina_HiSeq_2000--SINGLE--Solanum_lycopersicum--AC_leaf_H3K27me3_Cornell_3--leaf--leaf

projectdir: /tsl/scratch/shrestha/lila_grandgeorge
